### ISSUE TITLE
Jigsaw Deit Target

### ISSUE THREAD

**Issue by doem97** [yingyichen-cyy/JigsawViT#2]
May I know [here](https://github.com/yingyichen-cyy/JigsawViT/blob/cb2e532a41505d1207704986711a46ec02af0a6f/imagenet/jigsaw-deit/models_jigsaw.py#L45)
The target is not used?

**Comment by yingyichen-cyy** [comment]
Hi, thank you for pointing it out. 
self.target is indeed not used and only the [ids_keep](https://github.com/yingyichen-cyy/JigsawViT/blob/cb2e532a41505d1207704986711a46ec02af0a6f/noisy-label/jigsaw-vit/model_jigsaw.py#L132C2-L132C2) is used as targets for jigsaw prediction.
We will delete it.
